version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: guia_app
      MONGO_INITDB_ROOT_PASSWORD: GuiaApp123
    volumes:
      - mongo_guia_app:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: guia_app
      ME_CONFIG_MONGODB_ADMINPASSWORD: GuiaApp123
volumes:
  mongo_guia_app: